# pylint: disable=unused-argument, invalid-name
"""
Helpers for pyFuzzer
"""

def get_dummy_ast() -> int:
    """Get A dummy AST
    which will print "Hello, World"
    
    Returns:
        int: data_ast_t address generated by native
    """

def dump_ast(addr: int) -> None:
    """Dump AST

    Args:
        addr (int): data_ast_t address generated by native extension
    """


def free_ast(addr: int) -> None:
    """Free AST
    
    Args:
        addr (int): data_ast_t address generated by native extension
    """
