# pylint: disable=unused-argument, invalid-name
"""
Target for pyFuzzer
fuzzing entry
"""

def run_mod(addr: int) -> None:
    """run mod_ty

    Args:
        addr (int): data_ast_t address generated by native extension
    """
